service: shopfast-api

frameworkVersion: '4'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: ${opt:stage, 'dev'}

  environment:
    USER_POOL_ID: ${env:USER_POOL_ID}
    USER_POOL_CLIENT_ID: ${env:USER_POOL_CLIENT_ID}

functions:
  createPayment:
    handler: src/handler.create_payment
    events:
      - httpApi:
          path: /payments
          method: post
          # authorizer: ${opt:offline,'NONE'}

  refundPayment:
    handler: src/handler.refund_payment
    events:
      - httpApi:
          path: /payments/refund
          method: post
          # authorizer: ${opt:offline,'NONE'}
