service: shopfast-api

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: dev

  environment:
    USER_POOL_ID: ${env:USER_POOL_ID}
    USER_POOL_CLIENT_ID: ${env:USER_POOL_CLIENT_ID}

functions:
  createPayment:
    handler: src/handler.create_payment
    events:
      - http:
          path: /payments
          method: post
          authorizer:
            type: jwt
            name: cognitoAuthorizer  # required
            identitySource: $request.header.Authorization
            scopes:
              - payment-service/payments.create

  refundPayment:
    handler: src/handler.refund_payment
    events:
      - http:
          path: /payments/refund
          method: post
          authorizer:
            type: jwt
            name: cognitoAuthorizer
            identitySource: $request.header.Authorization
            scopes:
              - payment-service/payments.refund
