service: shopfast-api

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: dev

  environment:
    USER_POOL_ID: !ImportValue ShopFast-UserPoolId
    USER_POOL_CLIENT_ID: !ImportValue ShopFast-UserPoolClientIdA

functions:

  createPayment:
    handler: src/handler.create_payment
    events:
      - http:
          path: /payments
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ShopFastApiGatewayAuthorizer
            scopes:
              - payment-service/payments.create

  refundPayment:
    handler: src/handler.refund_payment
    events:
      - http:
          path: /payments/refund
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ShopFastApiGatewayAuthorizer
            scopes:
              - payment-service/payments.refund

resources:
  Resources:

    ShopFastApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: ShopFastCognitoAuthorizer
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        ProviderARNs:
          - !ImportValue ShopFast-UserPoolArn
